#!/usr/bin/env ruby

require 'fileutils'

dir = File.expand_path "~/Library/Developer/Xcode/Templates/File\ Templates/Custom\ Templates"
FileUtils.mkdir_p dir

Dir.glob("*.xctemplate").each do |name|
  template = "#{dir}/#{name}"
  FileUtils.rm_r template if File.exists? template
  FileUtils.cp_r name, template
end
